* Feldolgozás qgisben
** A vonal felkeresése
Az ~útnyilvántartás~ réteg segítségével megkeresem a térképet. A
leggyorsabb a rétegre állva az ~Attribútum tábla megnyitása~ gombbal a
táblázatot megnyitva, az oszlop számára kattintani.

A térkép arányai alapján kb. jól belőhető a terület, s megtalálható az út.

** A vonal kijelölése ha csak néhány szakaszból áll
A megtalált útvonalat az "Egy elem szelektálása" gombbal, a ~Ctrl~
gombot nyomva tartva végik kell kattintani. A kiválasztott szakasz
sárga lesz.  Ha tévesen választottam ki valamit, akkor csak rá kell
kattintani, természetesen a ~Ctrl~-t nem elengedve.

Fontos, hogy bal gombos kattintást csak ~Ctrl~ segítségével csináljak,
mert különben az eddigi kijelölés eltűnik. Két egérgombot nyomva
eltolhatom a térképet. Görgető gombbal belenagyíthatok. Oda nagyít,
ahol a kurzor van.

A kijelölt utat másolom a vágólapra (~Ctrl-C~).

** A vonal kiválasztása ha sok kicsi szegmensből áll
Előfordul, hogy a hosszabb szakaszok között több pici szegmens van.

Ebben az esetben érdemes használni az ~Úthálózat modul~-t, amit
bekapcsolva és a ~Vektor -> Úthálózat -> Beállítások~-ra OK-t ütve be
lehet izzítani.

A ~Beállítások -> Tárgyraszter beállítások~ menü segítségével érdemes
egy kis toleranciát adni a törésponthoz. Kísérletként 20-at adtam. Jól
működött vele.

Ez a modul kijelöli a csatlakozó vektorokat. Meg kell adni a kezdőpontot
és a végpontot. Némi vizsgálat után megjelenik piros vonallal az eredmény.
Ez egy vektor, amit a modul felületén található gombbal exportálni lehet
egy új rétegbe. Az új réteget aktívvá téve a vágólapra másolható.


** A kijelölt vektor beillesztése

Ha az adott lapon az első vektort akarom elmenteni, akkor új rétegként
a ~Szerkeszt -> Elem beillesztése mint -> Új vektor réteg~
segítségével tudom beilleszteni.

A frissen létrehozott réteget szerkeszthetővé kell tenni. A következő utat
már mint beillesztés a vágólapról hozzá lehet adni. A kimásolás után az
eredmény réteget kell aktuálissá tenni.

** Összefűzés
Ha több darabban másoltam be a vektort, akkor célszerű az összefűzést
rögtön a bemásolás után megcsinálni.  Ha több térképről bemásolt utat
fűzünk össze természetesen később is kijelölhetők a darabok a
szerkeszthető eredmény térképen.

Az összefűzés funkció a ~Szerkeszt -> Szelektált elemek összevonása~
kiválasztásával érhető el. Nekem a nem összefüggő vonalakat is simán
összefűzte, így a hiányzó szakaszok berajzolása helyett a táblázatban
jelöltem a hiányokat.

Néhányszor előfordult, hogy több utat sikerült összevonnom. Talán kijelölve
maradt az előző, vagy nem tökéletes a módszer. Ilyenkor az adatbázisban
kijelöltem a legutolsót, töröltem, s ha látszólag nem volt ellentmondás,
akkor újra bemásoltam. Úrakiválasztás nélküli megoldást lásd lejjebb a
[[V%C3%A9letlen%C3%BCl%20%C3%B6sszef%C5%B1z%C3%B6tt%20k%C3%BCl%C3%B6n%C3%A1ll%C3%B3%20elemek%20darabol%C3%A1sa][Véletlenül összefűzött különálló elemek darabolása]] fejezetben

Összefűzésnél mindig az utoljára kiválasztott elem adattáblabeli
értékeit rendeli az összevont elemhez.

** Leíró adatok
Az összefűzés után az adattáblába beírom a számot, a nevet és a hosszt.
Az első vektornál létre kell hozni a megfelelő mezőket. Azonosítónak
meghagytam az alapértelmezett =FID= mezőt. Az út nevének 20 karakter hosszú
mezőt (=Név=), a hossznak 8+2-es valós mezőt (=Hossz=) hoztam létre.

Az érték adás az azonosítónál és a névnél egyszerő beírás. A hossznál az
abakuszra kattintva a ~Létező mezők frissítése~ dobozt be kell kattintani,
kiválasztani a ~Hossz~-t, és beírni a ~Kifejezés~-hez, hogy ~$length~. 

A ~Hossz~ mezőt érdemes csak időnként frissíteni a sok kattintás miatt.
Mindig láthatóvá teszem az ~Attribútum tábla~ ablakot.

** Darabolás
A Hurok utat újra kellett darabolnom. Ott jól jött az alábbi leírás:

I often need to split a linestring exactly on one of his existing
internal vertices, but I can't find a way; I've tried the tool "Split
Features" thinking that it could snap on vertices.

In Snapping Options (Settings menu) enable snapping (better snapping
to vertex only in your case as suggested in comments) for your layer,
then using Split feature tool make a left click on the one blank space
on side of the line, then make left click on the vertex where the
split should occur and in the end make a right click on the blank
space on the other side of the line.

Végül újra beolvastam, mert kísérletezés köben néhány node elmozdult.

** Véletlenül összefűzött különálló elemek darabolása
Két hosszabb utat összerántott a program. Kimásoltam őket egy új rétegre,
összekötöttem őket egy vonallal és összefűztem, majd mint elemet elvágtam
őket. Az eredeti rétegen a problémás vonalat kitöröltem, majd a szétvágott
változatát visszamásoltam. Úgy tűnik rendben.

** Út a határ szélén
I have a layer that contains roads in polygons and I need to get
>> central lines of the polygons. When I convert directly from polygons
>> to lines, I get two lines for each part of the road representing road
>> "boundaries" which isn't good.
>>
>>
>> There's a procedure using GRASS that you might choose. It involves
>> converting the polygons to a GRASS raster, then running the GRASS module
>> r.thin, and then converting back to a vector.
>> Here's an old thread that mentions the method:

If vector map contains only rivers, You could try
out v.to.rast and then r.thin till You get something similar to river
and then convert back to vectors with r.to.vect.

Two difficulties:
- you have to set the resolution fairly high in order to keep the road's
  shapes, but then the raster might be too large to work with on a large area
- and you loose the attribute table on the way...

* Probléma
Községhatárnál az út két darabban, nem csatlakozó vonalként
14004

15 térképen Hátsó völgyi út csak részlethatárként van meg!

Sok helyen nem egyértelmű az elhatárolás, nevek. Névtelen utaknál
kérdőjeles nevet adtam.

** TODO Györkei út hossza változott!

<2015-03-08 v>
17 térkép bal alsó sarok kék, névtelen vonal nincs a vonalak között
17002 legvégét nem jelöltem, az erdőtömb határán kívül.
17005 Rozsnoki új dózerút egy vicc. A régi alapján kivett területet kerülgeti. (1)
17006 Rozsnoki régi dózerút (1)
23101 Kopott hutai út (1)
23103 Glóbuszi út (1)
23110 Fényes-pusztai út Maradt rajta egy pöcök

15009 és 14011 Ugyan az az út?

14016 Tekeresi út vége egy részlethatár vagy term. vonal

